grocery_items = [
  {
    '_id': '1',
    'name': 'Apple',
    'image': '/images/Apple.jpg',
    'description':
      'Apples are some of the most popular and delicious fruits on the planet. There are more than 7,500 varieties of this delicious fruit. China Fuji Apple is one of them. Fuji apples are typically round and range from large to very large, averaging 75 mm in diameter. They contain between 9–11% sugars by weight and have a dense flesh that is sweeter and crisper than many other apple cultivars, making them popular with consumers around the world. Fuji apples also have a very long shelf life compared to other apples, even without refrigeration. With refrigeration, Fuji apples can remain fresh for up to a year. Fuji apples are a variety of apple that originates in Japan. They are yellowish-green in color with red highlights. Harvested in September and October. Fuji apples are a healthy addition to most diets. They have no fat, sodium or cholesterol. A medium-sized apple weights about 154 grams and provides 80 calories. The FDA categorizes Fuji apples as a low-calorie food. Calories come from carbohydrates, proteins, fats and sugar. Any calories that your body does not use is stored as fat. A medium-sized Fuji apple also provides 170 milligrams of potassium. It offers 20 percent of the recommended daily value for vitamin C and 2 percent of the DV for vitamin A, calcium and iron, based on a 2,000-calorie diet.',
    'brand': 'China',
    'category': 'Fruits',
    'price': 159,
    'countInStock': 30,
    'rating': 0.0,
    'numReviews': 3,
  },
  {
    '_id': '2',
    'name': 'Egg',
    'image': '/images/Egg.jpg',
    'description':
      'Eggs are an all-natural source of high-quality protein and a number of other nutrients, all for 70 calories an egg. 100% fresh and healthy.',
    'brand': 'Local Layer',
    'category': 'Breakfast',
    'price': 99,
    'countInStock': 5,
    'rating': 4.7,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Onion',
    'image': '/images/Onion.jpg',
    'description':
      'Though all vegetables are important for health, certain kinds offer unique benefits. Onions are members of the Allium genus of flowering plants that also includes garlic, shallots, leeks and chives. These vegetables contain various vitamins, minerals and potent plant compounds that have been shown to promote health in many ways. In fact, the medicinal properties of onions have been recognized since ancient times, when they were used to treat ailments like headaches, heart disease and mouth sores.',
    'brand': 'Local',
    'category': 'Vegetables',
    'price': 49,
    'countInStock': 50,
    'rating': 4.4,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Potato',
    'image': '/images/Potato.jpg',
    'description':
      'Potato is a very healthy food and popular vegetable all over the world. Potatoes are available year-round as they are harvested somewhere every month of the year. potato\'s have lots of variety.these Potatoes are comparatively bigger than regular Potatoes.potatoes contain a goodly amount of carbohydrate(starch and sugar) they are also a storehouse for many vitamins and minerals.With the exception of vitamin A, potatoes have at least some of just about every nutrient, including fiber.Potatoes are relatively low in calories.',
    'brand': 'Local Diamond',
    'category': 'Vegetables',
    'price': 25,
    'countInStock': 30,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Tomato',
    'image': '/images/Tomato.jpg',
    'description':
      'The tomato is consumed in diverse ways, including raw, as an ingredient in many dishes, sauces, salads, and drinks. While it is botanically a fruit, it is considered a vegetable for culinary purposes. The fruit is rich in lycopene, which may have beneficial health effects.',
    'brand': 'Local Red',
    'category': 'Vegetables',
    'price': 59,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Butter',
    'image': '/images/Butter.jpg',
    'description':
      'Aarong butter is a dairy product made by fresh or fermented cream or milk, to separate the butterfat from the buttermilk. It is generally used as a spread as well as in cooking, such as baking, sauce making, and pan frying. Butter consists of butterfat, milk proteins and water. Most frequently made from cows\' milk, butter can also be manufactured from the milk of other mammals, including sheep, goats, buffalo, and yaks.Salt, flavorings and preservatives are sometimes added to butter.Rendering butter produces clarified butter or ghee, which is almost entirely butterfat.',
    'brand': 'Aarong',
    'category': 'Breakfast',
    'price': 200,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 12,
  },
]
