export const GROCERY_ITEM_LIST_REQUEST = 'GROCERY_ITEM_LIST_REQUEST';
export const GROCERY_ITEM_LIST_SUCCESS = 'GROCERY_ITEM_LIST_SUCCESS';
export const GROCERY_ITEM_LIST_FAIL = 'GROCERY_ITEM_LIST_FAIL';

export const GROCERY_ITEM_DETAILS_REQUEST = 'GROCERY_ITEM_DETAILS_REQUEST';
export const GROCERY_ITEM_DETAILS_SUCCESS = 'GROCERY_ITEM_DETAILS_SUCCESS';
export const GROCERY_ITEM_DETAILS_FAIL = 'GROCERY_ITEM_DETAILS_FAIL';

export const GROCERY_ITEM_DELETE_REQUEST = 'GROCERY_ITEM_DELETE_REQUEST';
export const GROCERY_ITEM_DELETE_SUCCESS = 'GROCERY_ITEM_DELETE_SUCCESS';
export const GROCERY_ITEM_DELETE_FAIL = 'GROCERY_ITEM_DELETE_FAIL';

export const GROCERY_ITEM_CREATE_REQUEST = 'GROCERY_ITEM_CREATE_REQUEST';
export const GROCERY_ITEM_CREATE_SUCCESS = 'GROCERY_ITEM_CREATE_SUCCESS';
export const GROCERY_ITEM_CREATE_FAIL = 'GROCERY_ITEM_CREATE_FAIL';
export const GROCERY_ITEM_CREATE_RESET = 'GROCERY_ITEM_CREATE_RESET';

export const GROCERY_ITEM_UPDATE_REQUEST = 'GROCERY_ITEM_UPDATE_REQUEST';
export const GROCERY_ITEM_UPDATE_SUCCESS = 'GROCERY_ITEM_UPDATE_SUCCESS';
export const GROCERY_ITEM_UPDATE_FAIL = 'GROCERY_ITEM_UPDATE_FAIL';
export const GROCERY_ITEM_UPDATE_RESET = 'GROCERY_ITEM_UPDATE_RESET';

export const GROCERY_ITEM_CRATE_REVIEW_REQUEST = 'GROCERY_ITEM_CRATE_REVIEW_REQUEST';
export const GROCERY_ITEM_CRATE_REVIEW_SUCCESS = 'GROCERY_ITEM_CRATE_REVIEW_SUCCESS';
export const GROCERY_ITEM_CRATE_REVIEW_FAIL = 'GROCERY_ITEM_CRATE_REVIEW_FAIL';
export const GROCERY_ITEM_CRATE_REVIEW_RESET = 'GROCERY_ITEM_CRATE_REVIEW_RESET';