export const GROCERY_ITEM_LIST_REQUEST = 'GROCERY_ITEM_LIST_REQUEST';
export const GROCERY_ITEM_LIST_SUCCESS = 'GROCERY_ITEM_LIST_SUCCESS';
export const GROCERY_ITEM_LIST_FAIL = 'GROCERY_ITEM_LIST_FAIL';

export const GROCERY_ITEM_DETAILS_REQUEST = 'GROCERY_ITEM_DETAILS_REQUEST';
export const GROCERY_ITEM_DETAILS_SUCCESS = 'GROCERY_ITEM_DETAILS_SUCCESS';
export const GROCERY_ITEM_DETAILS_FAIL = 'GROCERY_ITEM_DETAILS_FAIL';